# Generated by Django 4.1.7 on 2023-03-01 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_apply_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='jop',
            new_name='job',
        ),
    ]
